name: Auto Deploy Next

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Kodları Runner içindeki kısa yola (yani senin projerine) indirir
          path: /app

      - name: Build and Deploy Next
        # Artık yol çok kısa ve temiz:
        working-directory: /app
        run: |
          # Bu komut çalıştığında dosyalar fiziksel klasöründe GÜNCELLENMİŞ olacak.
          docker compose up -d --build next
          docker image prune -f