name: Auto Deploy Next

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Deploy Next

        working-directory: ./02-subdomains
        run: |
          docker compose up -d --build next
          docker image prune -f